# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='fail_times',
            field=models.IntegerField(default=0),
        ),
    ]
