# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_info_fail_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='passWord',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
