# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160802_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='fail_times',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='integral',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
